In [1]:
from google.colab import files

uploaded = files.upload()

Saving warehouse_status.csv to warehouse_status.csv

In [2]:
from google.colab import files

uploaded = files.upload()

Saving inventory_products.csv to inventory_products.csv

In [3]:
import pandas as pd

products_df = pd.read_csv("inventory_products.csv")
warehouse_df = pd.read_csv("warehouse_status.csv")

print(products_df)
print()
print(warehouse_df)

   product_id product_name     category  reorder_level
0         101       Laptop  Electronics             10
1         102        Mouse  Electronics             20
2         103     Keyboard  Electronics             15

   warehouse_id        warehouse_name  total_stock  stock_status
0             1     Chennai Warehouse           28  Understocked
1             2  Coimbatore Warehouse          215   Overstocked
2             3     Madurai Warehouse           12  Understocked

In [5]:
inventory_df = pd.DataFrame({
    "product_id":[101,102,103],
    "warehouse_id":[1,1,2]
})

inventory_df

   product_id  warehouse_id
0         101             1
1         102             1
2         103             2

In [6]:
master_df = pd.merge(
    inventory_df,
    products_df,
    on="product_id"
)

master_df

   product_id  warehouse_id product_name     category  reorder_level
0         101             1       Laptop  Electronics             10
1         102             1        Mouse  Electronics             20
2         103             2     Keyboard  Electronics             15

In [7]:
master_df = pd.merge(
    master_df,
    warehouse_df,
    on="warehouse_id"
)

master_df

,product_id,warehouse_id,product_name,category,reorder_level,warehouse_name,total_stock,stock_status
0,101,1,Laptop,Electronics,10,Chennai Warehouse,28,Understocked
1,102,1,Mouse,Electronics,20,Chennai Warehouse,28,Understocked
2,103,2,Keyboard,Electronics,15,Coimbatore Warehouse,215,Overstocked

In [8]:
master_df["reorder_flag"] = master_df["stock_status"].apply(
    lambda x: "YES" if x=="Understocked" else "NO"
)

master_df

,product_id,warehouse_id,product_name,category,reorder_level,warehouse_name,total_stock,stock_status,reorder_flag
0,101,1,Laptop,Electronics,10,Chennai Warehouse,28,Understocked,YES
1,102,1,Mouse,Electronics,20,Chennai Warehouse,28,Understocked,YES
2,103,2,Keyboard,Electronics,15,Coimbatore Warehouse,215,Overstocked,NO

In [9]:
master_df.to_csv(
    "master_inventory.csv",
    index=False
)

print("File generated successfully")

File generated successfully

In [10]:
from google.colab import files

files.download("master_inventory.csv")

In [11]:
from google.colab import files

uploaded = files.upload()

Saving stock_movements.csv to stock_movements.csv

In [12]:
import pandas as pd
import numpy as np

# Load data
df = pd.read_csv("stock_movements.csv")

# Calculate stock levels
stock_summary = (
    df.groupby(
        ["product_id",
         "product_name",
         "reorder_level"]
    )["quantity"]
    .sum()
    .reset_index()
)

stock_summary.rename(
    columns={"quantity":"current_stock"},
    inplace=True
)

# Create reorder flag
stock_summary["status"] = np.where(
    stock_summary["current_stock"] <
    stock_summary["reorder_level"],
    "REORDER",
    "OK"
)

# Filter low stock items
low_stock = stock_summary[
    stock_summary["status"]=="REORDER"
]

# Save report
low_stock.to_csv(
    "low_stock_report.csv",
    index=False
)

print("Low Stock Report Generated Successfully")
print()
print(low_stock)

Low Stock Report Generated Successfully

   product_id product_name  reorder_level  current_stock   status
0         101       Laptop             10              5  REORDER
1         102        Mouse             20             15  REORDER
2         103     Keyboard             15              5  REORDER
3         104      Monitor             10              5  REORDER
4         105      Printer             12              8  REORDER